### ISSUE TITLE
[PE-D][Tester D] Missing Logo in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T14-2/tp#84] opened 2023-03-31 17:00 UTC
Even though the homepage has the project logo, it is missing in the user guide

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: vsamarth/ped#3

**Comment by shuimeihe** [comment] 2023-04-01 13:36
Duplicate of #80

**Closed** 2023-04-04 12:11 UTC
Labels: duplicate
